# Generated by Django 3.0.2 on 2020-03-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
