# Generated by Django 3.0.2 on 2020-03-08 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
