# Generated by Django 3.0.2 on 2020-03-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_account_hdhsnf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='hdhsnf',
        ),
    ]
